"""Frozen paper and repository contracts for the 2026-07-21 reproduction batch."""

METHODS = {
    "patch_mix_cl": {
        "display_name": "Patch-Mix Contrastive Learning",
        "env": "acoustic-patchmix-r3",
        "repo_url": "https://github.com/raymin0223/patch-mix_contrastive_learning",
        "commit": "836b09fea1b70eb29fe0b25afa481286b56f5104",
        "license_expected": "MIT",
        "protocol_name": "faithful_test_selected",
        "split_policy": "official_recording_split",
        "paper_target": {"sp_mean": 81.66, "sp_sd": 3.83, "se_mean": 43.07, "se_sd": 2.80, "score_mean": 62.37, "score_sd": 0.61, "runs": 5},
        "secondary_binary_score": {"mean": 68.71, "sd": 0.59},
        "preprocessing": {"sample_rate": 16000, "seconds": 8, "padding": "repeat_with_fade", "n_mels": 128, "feature": "fbank", "specaugment": True},
        "model": "AST base384, ImageNet+AudioSet initialization",
        "training": {"optimizer": "AdamW via repo optimizer=adam", "lr": 5e-5, "weight_decay": 1e-6, "batch_size": 8, "epochs": 50, "cosine": True, "ema_beta": 0.5, "temperature": 0.06, "proj_dim": 768, "alpha": 1.0, "mix_beta": 1.0, "seed": 1},
        "selection": "official test every epoch; best checkpoint by test ICBHI Score",
        "checkpoint_gate": "exact original audioset_10_10_0.4593.pth identity",
        "contract_repo_alignment": "aligned_except_checkpoint_identity_and_missing_bundled_data_files",
    },
    "pafa": {
        "display_name": "Patient-Aware Feature Alignment",
        "env": "acoustic-pafa-r3",
        "repo_url": "https://github.com/wa976/PAFA",
        "commit": "e49e294d0db0d6af10ac46290512b9c85d3f71e1",
        "license_expected": None,
        "protocol_name": "faithful_test_selected",
        "split_policy": "official_recording_split",
        "paper_target": {"sp_mean": 82.05, "sp_sd": 1.95, "se_mean": 47.63, "se_sd": 2.23, "score_mean": 64.84, "score_sd": 0.60, "runs": 5},
        "secondary_binary_score": {"mean": 72.08, "sd": None},
        "preprocessing": {"sample_rate": 16000, "seconds": 5, "padding": "repeat_or_truncate", "n_mels": 128, "specaugment": False, "repo_flag": "--nospec"},
        "model": "BEATs_iter3+ AS2M",
        "training": {"optimizer": "Adam", "lr": 5e-5, "weight_decay": 1e-6, "batch_size": 32, "epochs": 100, "cosine": True, "ema_beta": 0.5, "lambda_pcsl": 50.0, "lambda_gpal": 0.0005, "w_ce": 1.0, "w_pafa": 1.0, "norm_type": "ln", "output_dim": 768, "seed": 1},
        "selection": "official test every epoch; best checkpoint by test ICBHI Score",
        "checkpoint_gate": "exact BEATs_iter3+ AS2M identity",
        "contract_repo_alignment": "aligned; no LICENSE and no author task checkpoint",
    },
    "mvst": {
        "display_name": "Multi-View Spectrogram Transformer",
        "env": "acoustic-mvst-r3",
        "repo_url": "https://github.com/wentaoheunnc/MVST",
        "commit": "51f93fa6ffa580d0819ccb59f861582927937264",
        "license_expected": None,
        "protocol_name": "author_repo_random_file_split_official_like",
        "split_policy": "sorted recordings; random.Random(1) shuffle; fixed 60/40 recording split",
        "paper_target": {"sp": 81.99, "se": 51.10, "score": 66.55, "runs": None},
        "single_view_targets": {"16x16_score": 62.55, "128x2_score": 62.94},
        "preprocessing": {"sample_rate": 16000, "spectrogram_shape": [256, 1024], "views": ["16x16", "32x8", "64x4", "128x2", "256x1"]},
        "model": "five AudioSet AST encoders followed by gated fusion",
        "training": {"encoder_optimizer": "AdamW", "encoder_lr": 5e-5, "encoder_weight_decay": 1e-6, "encoder_batch_size": 8, "encoder_epochs": 50, "fusion_optimizer": "AdamW", "fusion_lr": 1e-3, "fusion_weight_decay": 1e-4, "fusion_epochs": 100, "seed": 1},
        "selection": "fusion official-like test partition every epoch; best checkpoint by test Score",
        "checkpoint_gate": "exact audioset_16_16_0.4422.pth identity and identical ordered cycle IDs across five views",
        "contract_repo_alignment": "major contradiction: paper calls settings official while executable repo uses fixed random file split",
    },
    "add_rsc": {
        "display_name": "Adaptive Differential Denoising for Respiratory Sounds Classification",
        "env": "acoustic-addrsc-r3",
        "repo_url": "https://github.com/deegy666/ADD-RSC",
        "commit": "e2b0f8213cb7ca451ef28757cb1329e17469fe72",
        "license_expected": None,
        "protocol_name": "no_unique_faithful_protocol",
        "split_policy": "two separate receipts required",
        "paper_target": {"ast_sp": 85.13, "ast_se": 45.94, "ast_score": 65.53, "resnet_sp": 83.76, "resnet_se": 34.18, "resnet_score": 58.97},
        "protocols": {
            "paper_declared_reconstruction": {"split": "official recording split", "sample_rate": 16000, "seconds": 8, "padding": "cyclic", "n_mels": 64, "window_size": 1024, "weight_decay": 0.1, "lr": 5e-5, "batch_size": 8, "epochs": 50, "beta": 0.5, "alpha": 0.02, "epsilon": 0.2},
            "author_repo_default_official_like": {"split": "random.Random(1) fixed 60/40 recording split", "n_mels": 128, "weight_decay": 1e-6, "lr": 5e-5, "batch_size": 8, "epochs": 50},
        },
        "model": "AST base with AudioSet initialization",
        "selection": "repository evaluates held-out partition every epoch and retains best score",
        "checkpoint_gate": "AST AudioSet checkpoint identity; no author task checkpoint",
        "contract_repo_alignment": "unresolved contradictions in n_mels, weight decay, split, and absent exact command",
    },
    "sg_scl": {
        "display_name": "Stethoscope-Guided Supervised Contrastive Learning",
        "env": "acoustic-sgscl-r3",
        "repo_url": "https://github.com/kaen2891/stethoscope-guided_supervised_contrastive_learning",
        "commit": "66564609595090b61540595d3d27764c00553086",
        "license_expected": None,
        "protocol_name": "metadata_aware_official_like_test_selected",
        "split_policy": "official_recording_split",
        "paper_target": {"sp_mean": 79.87, "sp_sd": 8.89, "se_mean": 43.55, "se_sd": 5.93, "score_mean": 61.71, "score_sd": 1.61, "runs": 5},
        "secondary_binary_score": {"sp_mean": 79.87, "sp_sd": 8.89, "se_mean": 57.97, "se_sd": 8.96, "score_mean": 68.93, "score_sd": 1.47},
        "preprocessing": {"sample_rate": 16000, "seconds": 8, "n_mels": 128, "feature": "fbank", "window_ms": 25, "shift_ms": 10},
        "model": "AST ImageNet+AudioSet plus device-aware contrastive projector",
        "training": {"optimizer": "AdamW via repo optimizer=adam", "lr": 5e-5, "weight_decay": 1e-6, "batch_size": 8, "epochs": 50, "cosine": True, "ema_beta": 0.5, "domain_adaptation2": True, "meta_mode": "dev", "proj_dim": 768, "temperature": 0.06, "alpha": 1.0, "target_type": "project1_project2block", "seed": 1},
        "selection": "official test every epoch; best checkpoint by test ICBHI Score",
        "checkpoint_gate": "exact original audioset_10_10_0.4593.pth identity",
        "contract_repo_alignment": "aligned; metadata-aware rather than audio-only; no LICENSE or task checkpoint",
    },
}
