name: acoustic-baseline-downstream
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - joblib==1.5.2
      - jupyter==1.1.1
      - numpy==1.26.4
      - pandas==2.3.3
      - scikit-learn==1.7.2
      - torch==2.12.1
